import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import React, { MouseEventHandler, useEffect, useState } from "react";
import SearchBar from "../components/SearchBar";
import { connectToDatabase } from "../utils/mongodb";
import { ObjectId } from "mongodb";

interface Data {
  _id: ObjectId;
  content?: string;
  inserted?: number;
  updated?: number;
}

const Home: NextPage = () => {
  const [data, setData] = useState<Array<Data>>([]);
  const [value, setValue] = useState("");
  const [invalidData, setinvalidData] = useState(true);
  const [editing, setEditing] = useState<{ id?: ObjectId | null; text?: string }>({text: ''});

  useEffect(() => {
    const fetchData = async () => {
      const res = await fetch("/api/todos");
      const data = await res.json();
      setData(data.todos);
      setinvalidData(false);
    };
    if (invalidData) fetchData();
  }, [invalidData]);

  const SubmitHandler = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    fetch(`/api/insert?content=${value}`, { method: "POST" })
      .then((res) => {
        if (res.status == 200) setinvalidData(true);
        setValue("");
      })
      .catch((err) => console.log(err));
  };

  const ChangeHandler = (e: React.ChangeEvent<HTMLInputElement>) => {
    let tmp_value = e.target.value;
    setValue(tmp_value);
  };

  const deleteHandler = (
    e: React.SyntheticEvent<HTMLButtonElement>,
    id: ObjectId
  ) => {
    e.preventDefault();
    fetch(`/api/delete?_id=${id}`, { method: "POST" })
      .then((res) => {
        if (res.status == 200) setinvalidData(true);
        setValue("");
      })
      .catch((err) => console.log(err));
  };

  const handleUpdateTodo = (
    e: React.SyntheticEvent<HTMLButtonElement>,
    id: ObjectId
  ) => {
    e.preventDefault();
    fetch(`/api/update?id=${id}&content=${editing?.text || ""}`, {
      method: "GET",
    })
      .then((res) => {
        if (res.status == 200) setinvalidData(true);
        setEditing({...editing, id: null, text: ''})

      })
      .catch((err) => console.log(err));
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SearchBar
        SubmitHandler={SubmitHandler}
        ChangeHandler={ChangeHandler}
        value={value}
      />
      <div>
        <ul>
          {data?.length > 0 &&
            data.map((todo, index) => (
              <li key={index}>
                {todo._id == editing?.id ? (
                  <input
                    value={editing?.text || ""}
                    onChange={(e: React.ChangeEvent<HTMLInputElement>) =>
                      setEditing({ ...editing, text: e.target.value })
                    }
                  ></input>
                ) : (
                  todo.content
                )}
                {editing?.text === "" ? (
                  <button
                    onClick={() =>
                      setEditing({ id: todo._id, text: todo.content })
                    }
                  >
                    edit
                  </button>
                ) : (
                  <button onClick={(e) => handleUpdateTodo(e, todo._id)}>
                    save
                  </button>
                )}
                <button onClick={(e) => deleteHandler(e, todo._id!)}>X</button>
              </li>
            ))}
        </ul>
      </div>
    </div>
  );
};
export default Home;
